Use URL-safe base64 encoding for auth tokens
zelloptt/zello-channel-api pull request #117
Opened 2020-10-14 14:15 UTC by ihorserba

2020-10-14 14:18 UTC, ihorserba commented
Not well-tested yet

2020-10-15 12:01 UTC, vocoded commented on auth/php/tokenmanager.class.php
> +     * Encode a string to base64 format.
```suggestion
     * Encodes a string to a URL-safe base64 format.
```

2020-10-15 12:19 UTC, ihorserba commented on auth/js/tokenmanager.js
> +   * Encode data to base64 format.
The idea was to explain users what is going on here.
If you don't like the original comment - I propose to change as following:
```
/**
 * Encodes data to a URL-safe base64 format.
 * @param data - A string or buffer to encode
 * @returns an URL-safe base64 encoded string
 * @link https://tools.ietf.org/html/rfc4648#section-5
 */
```

2020-10-15 12:23 UTC, ihorserba commented on auth/js/tokenmanager.js
> -    const signature = sign.sign(privateKey, 'base64');
We need a signed data not being encoded with base64 here.
`crypto.sign()` without second argument returns an instance of Buffer.
We use this buffer in base64UrlEncode() to encode it URL-safe.

2020-10-15 12:24 UTC, ihorserba commented on auth/php/tokenmanager.class.php
> +     * Encode a string to base64 format.
The idea was to explain users what is going on here.
If you don't like the original comment - I propose to change as following:
```
/**
 * Encodes data to a URL-safe base64 format.
 * @param data - A string or buffer to encode
 * @returns an URL-safe base64 encoded string
 * @link https://tools.ietf.org/html/rfc4648#section-5
 */
```

2020-10-15 12:28 UTC, vocoded commented on auth/js/tokenmanager.js
> +   * Encode data to base64 format.
My suggestion is to be clearer in the first sentence, the rest of the commentblock is fine.

2020-10-15 12:28 UTC, vocoded commented on auth/js/tokenmanager.js
> -    const signature = sign.sign(privateKey, 'base64');
makes sense, thanks

2020-10-15 12:29 UTC, vocoded commented on auth/php/tokenmanager.class.php
> +     * Encode a string to base64 format.
see above

2020-10-15 12:40 UTC, ihorserba commented on auth/js/tokenmanager.js
> +   * Encode data to base64 format.
Need to explain where these '+', '/' and '=' have appeared from.
Lets add a line like:
```
Encode data to common base64.
```
so the comment is:
```
 /**
   * Encodes data to a URL-safe base64 format.
   * Encode data to common base64.
   * Replace '+' and '/' symbols with '-' and '_' respectively.
   * Remove trailing '='.
   * @param data - A string or buffer to encode
   * @returns an URL-safe base64 encoded string
   * @link https://tools.ietf.org/html/rfc4648#section-5
   */
```

2020-10-15 13:28 UTC, ihorserba commented on auth/php/tokenmanager.class.php
> +     * Encode a string to base64 format.
I would like to add one more explanation line - see in the previous comment block

2020-10-19 12:49 UTC, vocoded commented on auth/js/tokenmanager.js
> +   * Encode data to base64 format.
These lines read almost the same:

```
   * Encodes data to a URL-safe base64 format.
   * Encode data to common base64.
```

I understand you want to maintain the detail, so perhaps use:

```
/**
   * Encodes data to a URL-safe base64 format by taking the standard base64 output,
   * replacing '+' and '/' symbols with '-' and '_' respectively, then removing any trailing '=' symbols
   *
   * @param data - A string or buffer to encode
   * @returns The URL-safe base64 encoded form of the data
   * @link https://tools.ietf.org/html/rfc4648#section-5
   */
```

2020-10-19 12:50 UTC, vocoded requested changes
The requested change is for the invalid syntax in the JS example

2020-10-19 12:50 UTC, vocoded commented on auth/js/tokenmanager.js
> +    Buffer.from
not sure where this line came from, it should be removed

2020-10-19 15:37 UTC, ihorserba commented on auth/js/tokenmanager.js
> +    Buffer.from
Fixed and verified js example

2020-10-19 15:37 UTC, ihorserba commented on auth/js/tokenmanager.js
> +   * Encode data to base64 format.
Replaced the comments for PHP and JS examples

2020-10-28 12:24 UTC, merged