Added support for dispatch call updates
zelloptt/zello-channel-api pull request #157
Opened 2021-09-23 11:14 UTC by ihorserba

Extend the JS SDK with dispatch calls support for the issue: https://github.com/zelloptt/zellowork.com/issues/2202
The logic depends on the zello-wss changes:

https://github.com/zelloptt/zello-wss/pull/79
https://github.com/zelloptt/zello-wss/pull/75

2021-09-27 12:05 UTC, vocoded requested changes

2021-09-27 12:05 UTC, vocoded commented on sdks/js/src/classes/session.js
> +         * The Session is receiving a dispatch call update
```suggestion
         * Incoming dispatch call status change information
```

2021-09-27 12:05 UTC, vocoded commented on sdks/js/src/classes/session.js
> +         * @event Session#dispatch_call_updated
there is no such event triggered

2021-09-27 12:05 UTC, vocoded commented on sdks/js/src/classes/session.js
> +         * @property {string} dispatcher user name of the dispatcher taken the call.
```suggestion
         * @property {string} dispatcher user name of the dispatcher who has taken the call.
```

2021-09-27 12:05 UTC, vocoded commented on sdks/js/src/classes/session.js
> +         * @property {string} dispatcher_display_name display name of the dispatcher taken the call.
```suggestion
         * @property {string} dispatcher_display_name display name of the dispatcher who has taken the call.
```

2021-09-27 12:05 UTC, vocoded commented on sdks/js/src/classes/session.js
> +         * @property {string} dispatcher_profile_picture an URL to a profile picture of the dispatcher taken the call.
```suggestion
         * @property {string} dispatcher_profile_picture profile picture URL of the dispatcher who has taken the call.
```

2021-09-27 12:05 UTC, vocoded commented on sdks/js/src/classes/session.js
> +   endDispatchCall(options = {}, userCallback = null) {
i don't think theres any need for an options object here, let's pass the call ID directly

2021-09-28 12:08 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +         * The Session is receiving a dispatch call update
changed

2021-09-28 12:08 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +         * @event Session#dispatch_call_updated
changed to `dispatch_call`

2021-09-28 12:08 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +         * @property {string} dispatcher_display_name display name of the dispatcher taken the call.
changed

2021-09-28 12:09 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +         * @property {string} dispatcher_profile_picture an URL to a profile picture of the dispatcher taken the call.
changed

2021-09-28 12:09 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +   endDispatchCall(options = {}, userCallback = null) {
changed

2021-11-17 23:42 UTC, vocoded commented on sdks/js/src/classes/session.js
> +        this.emit(Constants.EVENT_DISPATCH_CALL, jsonData);
to avoid future collisions with receiving a new dispatch call, let's change this to `EVENT_DISPATCH_CALL_STATUS`

2021-11-18 18:03 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +        this.emit(Constants.EVENT_DISPATCH_CALL, jsonData);
Changed. We have to change the appropiate event in [kiosk](https://github.com/zelloptt/zellowork.com/blob/f37f64d70c4084ac393b834290d14e72d18eed61/kiosk/index.html)
and in [Bilka PoC kiosk](https://github.com/zelloptt/zellowork.com/blob/f37f64d70c4084ac393b834290d14e72d18eed61/kiosk/ui.html)
once SDK is recompiled

2021-11-18 18:29 UTC, vocoded commented on sdks/js/src/classes/session.js
> +   endDispatchCall(call_id, userCallback = null) {
minor, parameter name conventions are camelcase, even though the server expects snake. so let's change `call_id` here to `callId` (and update docs)

2021-11-18 21:15 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +   endDispatchCall(call_id, userCallback = null) {
Changed

2021-11-19 13:52 UTC, vocoded approved these changes

2021-12-29 18:31 UTC, merged