Init player before incoming message emitted
zelloptt/zello-channel-api pull request #180
Opened 2022-05-24 13:15 UTC by ihorserba

2022-05-24 16:01 UTC, ihorserba commented on sdks/js/src/classes/sdk.js
> +    library.IncomingMessage.PersistentPlayer.init().catch((err) => {
It's problematic.
The deferred in the sdk `init()` resolves once all scripts have been loaded.
And the player's `init()` resolves after a user action.

Maybe you have a better idea than just logging to the console in case of player init failed?

2022-05-24 17:17 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +        }).catch((err) => console.error('Failed to init incoming message:', err));
Added a new event for this `incoming_voice_failed`

2022-05-24 17:17 UTC, ihorserba commented
Added uninit of the player once it was failed.

2022-05-24 17:18 UTC, ihorserba commented
@vocoded please take a look once more

2022-05-24 17:55 UTC, vocoded commented on sdks/js/src/classes/constants.js
> +  EVENT_INCOMING_VOICE_FAILED: 'incoming_voice_failed',
let's call this `incoming_voice_fail_start` to match the existing style of `session_fail_connect`

2022-05-24 17:55 UTC, vocoded commented on sdks/js/src/classes/incomingMessage.js
> +      this.session.on([Constants.EVENT_INCOMING_VOICE_DID_STOP, this.instanceId], this.incomingVoiceDidStopHandler);
is there any reason these two session handlers should not be added in the `initSessionHandlers` method?

2022-05-24 17:55 UTC, vocoded commented on sdks/js/src/classes/sdk.js
> +    library.IncomingMessage.PersistentPlayer.init().catch((err) => {
well, what i mean is we have:

```
if (shouldInitDefaultPlayer) {
        Sdk.initDefaultPlayer(options);
}
dfd.resolve();
```

and instead we could have:

```
if (shouldInitDefaultPlayer) {
    Sdk.initDefaultPlayer(options).then(() => { dfd.resolve(); }).catch(() => { dfd.reject(); });
}
```

if you return the promise here rather than catch

2022-05-24 18:06 UTC, ihorserba commented on sdks/js/src/classes/sdk.js
> +    library.IncomingMessage.PersistentPlayer.init().catch((err) => {
In this case sdk init is resolved only after player init is resolved.
And the player init resolves after user's gesture.

So for the user it would look like sdk is not loaded until mouse is clicked.

2022-05-24 18:13 UTC, vocoded commented on sdks/js/src/classes/sdk.js
> +    library.IncomingMessage.PersistentPlayer.init().catch((err) => {
i see, that's difficult. i guess the better approach would be to allow the caller to pass a callback in the options which would be invoked on an error

2022-05-25 10:46 UTC, ihorserba commented on sdks/js/src/classes/incomingMessage.js
> +      this.session.on([Constants.EVENT_INCOMING_VOICE_DID_STOP, this.instanceId], this.incomingVoiceDidStopHandler);
Moved.
Renamed also `initSessionHandlers` -> `initEventHandlers`

2022-05-25 10:46 UTC, ihorserba commented on sdks/js/src/classes/constants.js
> +  EVENT_INCOMING_VOICE_FAILED: 'incoming_voice_failed',
Renamed

2022-05-25 10:53 UTC, ihorserba commented on sdks/js/src/classes/sdk.js
> +    library.IncomingMessage.PersistentPlayer.init().catch((err) => {
It seems fine to me with the current implementation.
If there was an error on the default player init - it's being logged.

Once incoming message started after that - it's being emitted on `incoming_voice_fail_start`. 

Furthermore, if the default player init was failed on the sdk init - there is another try [on the starting of an incoming message](https://github.com/zelloptt/zello-channel-api/blob/90f9b37544b1582de69fbf673c9b963726d95b59/sdks/js/src/classes/incomingMessage.js#L154-L161).

2022-05-25 10:55 UTC, ihorserba commented
Addressed all the comments,
updated pcm-player with the it's latest `master`,
increased the major version,
rebuilt SDK.

It's ready for another look.

2022-05-25 12:03 UTC, vocoded requested changes

2022-05-25 12:03 UTC, vocoded commented on sdks/js/src/classes/sdk.js
> +    library.IncomingMessage.PersistentPlayer.init().catch((err) => {
a log statement is not useful programmatically, though. for the other events you mentioned, would it be clear that the root cause is due to the player init failing?

i don't have really strong feelings about this, we don't need to address it now, but it may come up in the future.

2022-05-25 12:03 UTC, vocoded commented on sdks/js/package.json
> +  "version": "0.9.0",
the changes in session are breaking, so we need to bump to 1.0.0

2022-05-25 21:45 UTC, ihorserba commented on sdks/js/package.json
> +  "version": "0.9.0",
Changed.
I've created a new branch [version_1_0_0](https://github.com/zelloptt/zello-channel-api/tree/version_1_0_0) to merge all the SDK work there. Once it looks good - I'll merge it to master.

2022-05-25 21:47 UTC, ihorserba commented on sdks/js/src/classes/sdk.js
> +    library.IncomingMessage.PersistentPlayer.init().catch((err) => {
Extended the incomingMessage init error, so it says that the problem is within the player init.

2022-05-26 12:56 UTC, ihorserba commented
Back merged [version_1_0_0](https://github.com/zelloptt/zello-channel-api/tree/version_1_0_0) to [init_player_before_incoming_message_emitted](https://github.com/zelloptt/zello-channel-api/tree/init_player_before_incoming_message_emitted). 
Rebuilt the SDK in order to resolve the conflicts.

2022-05-31 19:56 UTC, vocoded approved these changes

2022-06-01 11:21 UTC, merged