Fix on stream stop for outgoing messages
zelloptt/zello-channel-api pull request #181
Opened 2022-05-25 11:36 UTC by ihorserba

2022-05-25 11:58 UTC, vocoded requested changes

2022-05-25 11:58 UTC, vocoded commented on sdks/js/src/classes/session.js
> +          break;
are we sure? if this can occur for an outgoing message then we should emit a different event for it rather than ignoring

2022-05-25 20:33 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +          break;
Added `outgoing_voice_did_stop`

2022-05-25 21:11 UTC, vocoded commented on sdks/js/src/classes/session.js
> +         * Outgoing voice message stopped from the outside
```suggestion
         * Outgoing voice message stopped by the server
```

2022-05-25 21:11 UTC, vocoded commented on sdks/js/src/classes/session.js
> +          this.emit(Constants.EVENT_OUTGOING_VOICE_DID_STOP, jsonData.stream_id);
what other jsonData exists in this condition? i'm not opposed to sending back only the stream ID but other attributes may be helpful

2022-05-25 21:39 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +          this.emit(Constants.EVENT_OUTGOING_VOICE_DID_STOP, jsonData.stream_id);
Nothing more.
Example:
```
{command: 'on_stream_stop', stream_id: 63503}
```

2022-05-26 12:34 UTC, vocoded approved these changes

2022-05-26 12:45 UTC, merged