Handle sdk load errors
zelloptt/zello-channel-api pull request #182
Opened 2022-05-31 07:38 UTC by ihorserba

Handle SDK loading errors.
Fixed the session connect promise to be rejected if failed to connect.

2022-05-31 11:53 UTC, vocoded requested changes
couple small things

2022-05-31 11:53 UTC, vocoded commented on sdks/js/src/classes/sdk.js
> +   *                                  or any of them was failed to load.
```suggestion
   *                                  or any of them failed to load.
```

2022-05-31 11:53 UTC, vocoded commented on sdks/js/src/classes/sdk.js
> +   *                   or rejects if any of the required components was failed to load.
```suggestion
   *                   or rejects if any of the required components failed to load.
```

2022-05-31 11:53 UTC, vocoded commented on sdks/js/src/classes/sdk.js
> +          userCallback.apply(userCallback, 'Unable to load ' + name);
apply takes a second argument that's an array. use `call` if you want to send the arguments one by one

2022-05-31 11:53 UTC, vocoded commented on sdks/js/src/classes/session.js
> +        dfd.reject(err);
does this need to be before the emit?

2022-05-31 18:04 UTC, ihorserba commented on sdks/js/src/classes/sdk.js
> +   *                                  or any of them was failed to load.
Changed

2022-05-31 18:07 UTC, vocoded commented on sdks/js/src/classes/session.js
> +    this.wsConnection.addEventListener('error', () => {
no argument is available?

2022-05-31 18:07 UTC, vocoded commented on sdks/js/src/vendor_opus-recorder_README.md
> +# Opus & Wave Recorder
where did this come from?

2022-05-31 18:08 UTC, ihorserba commented on sdks/js/src/classes/session.js
> -    this.wsConnection.addEventListener('error', (err) => {
There is no useful information here in `err` parameter.

2022-05-31 18:09 UTC, ihorserba commented on sdks/js/src/vendor_opus-recorder_README.md
> +# Opus & Wave Recorder
Already removed, commited by mistake

2022-05-31 18:10 UTC, ihorserba commented on sdks/js/src/classes/session.js
> +    this.wsConnection.addEventListener('error', () => {
This event here is useless - it provides no information about the error

2022-05-31 22:09 UTC, vocoded commented on sdks/js/src/classes/session.js
> +    this.wsConnection.addEventListener('error', () => {
i think it's still better to pass it along, perhaps in the future a better version of the library will improve it

2022-06-01 13:15 UTC, vocoded approved these changes

2022-06-01 13:29 UTC, merged